#pragma once

#define STR_HELPER(x) #x
#define STR(x) STR_HELPER(x)

#define MULTICAD_VERSION_MAJOR 0
#define MULTICAD_VERSION_MINOR 2
#define MULTICAD_VERSION_PATCH 0
#define MULTICAD_VERSION_STR STR(MULTICAD_VERSION_MAJOR) "." STR(MULTICAD_VERSION_MINOR) "." STR(MULTICAD_VERSION_PATCH)

#define SS_VERSION_MAJOR 1
#define SS_VERSION_MINOR 0
#define SS_VERSION_STR STR(SS_VERSION_MAJOR) "." STR(SS_VERSION_MINOR)
#define SS_GAME_STR "SS v" SS_VERSION_STR

#define SS_GOLD_VERSION_MAJOR 1
#define SS_GOLD_VERSION_MINOR 21
#define SS_GOLD_VERSION_STR STR(SS_GOLD_VERSION_MAJOR) "." STR(SS_GOLD_VERSION_MINOR)
#define SS_GOLD_GAME_STR "SS Gold v" SS_GOLD_VERSION_STR

#define SS_GOLD_HD_VERSION_MAJOR 1
#define SS_GOLD_HD_VERSION_MINOR 2
#define SS_GOLD_HD_VERSION_STR STR(SS_GOLD_HD_VERSION_MAJOR) "." STR(SS_GOLD_HD_VERSION_MINOR)
#define SS_GOLD_HD_GAME_STR "SS Gold HD v" SS_GOLD_HD_VERSION_STR

#define SS_HD_MOD_TG_LINK "t.me/ss_hd_mod"
#define SS_HD_MOD_AUTHOR_EMAIL "ivanishin.vladislav@gmail.com"
