#pragma once

#define STR_HELPER(x) #x
#define STR(x) STR_HELPER(x)

// MultiCAD version
#define MULTICAD_VERSION_MAJOR 0
#define MULTICAD_VERSION_MINOR 3
#define MULTICAD_VERSION_PATCH 0
#define MULTICAD_VERSION_STR STR(MULTICAD_VERSION_MAJOR) "." STR(MULTICAD_VERSION_MINOR) "." STR(MULTICAD_VERSION_PATCH)

// Sudden Strike (v1.0) version
#define SS_VERSION_MAJOR 1
#define SS_VERSION_MINOR 0
#define SS_VERSION_STR STR(SS_VERSION_MAJOR) "." STR(SS_VERSION_MINOR)
#define SS_GAME_STR "SS v" SS_VERSION_STR

// Sudden Strike (v1.2) version
#define SS_V1_2_VERSION_MAJOR 1
#define SS_V1_2_VERSION_MINOR 2
#define SS_V1_2_VERSION_STR STR(SS_V1_2_VERSION_MAJOR) "." STR(SS_V1_2_VERSION_MINOR)
#define SS_V1_2_GAME_STR "SS v" SS_V1_2_VERSION_STR

// Sudden Strike Gold (v1.21) version
#define SS_GOLD_VERSION_MAJOR 1
#define SS_GOLD_VERSION_MINOR 21
#define SS_GOLD_VERSION_STR STR(SS_GOLD_VERSION_MAJOR) "." STR(SS_GOLD_VERSION_MINOR)
#define SS_GOLD_GAME_STR "SS Gold v" SS_GOLD_VERSION_STR

// Sudden Strike HD v1.1 version
#define SS_HD_VERSION_MAJOR 1
#define SS_HD_VERSION_MINOR 1
#define SS_HD_VERSION_STR STR(SS_HD_VERSION_MAJOR) "." STR(SS_HD_VERSION_MINOR)
#define SS_HD_GAME_STR "SS HD v" SS_HD_VERSION_STR

// Sudden Strike Gold HD v1.2 version
#define SS_GOLD_HD_VERSION_MAJOR 1
#define SS_GOLD_HD_VERSION_MINOR 2
#define SS_GOLD_HD_VERSION_STR STR(SS_GOLD_HD_VERSION_MAJOR) "." STR(SS_GOLD_HD_VERSION_MINOR)
#define SS_GOLD_HD_GAME_STR "SS Gold HD v" SS_GOLD_HD_VERSION_STR

#define SS_HD_MOD_TG_LINK "tg: @ss_hd_mod"
#define SS_HD_MOD_AUTHOR_EMAIL "ivanishin.vladislav@gmail.com"
